/* THIS IS A BINARY PRINTER */
#include "master.h" /* CUSTOM HEADER INCLUDE.
		     * HERE WE ADD ALL THE HEADER */

/* WE SHALL DO IT BY MEANS OF DEFINE */
#define BYTE_TO_BINARY_PATTERN "%c%c%c%c%c%c%c%c" /* DEFINES
						A PRINTF THAT PRINTS
						8 BITS AS CHARACTERS */

#define BYTE_DT unsigned char /* BYTE DATA TYPE - ALIAS FOR UNSIGNED CHAR*/

/* MACRO THAT CONVERTS A BYTE'S BITS INTO EIGHT '1' OR '0' CHARACTERS
 * FOR PRINTING BY MEANS OF PRINTF (INCLUDED IN <STDIO.H> */
#define BYTE_TO_BINARY(byte) \
	((byte) & 0x80 ? '1' : '0'),/* TEST BIT 7 : 0x80 - 1000 0000 */ \
	((byte) & 0x40 ? '1' : '0'),/* TEST BIT 6 : 0x40 - 0100 0000 */ \
	((byte) & 0x20 ? '1' : '0'),/* TEST BIT 5 : 0x20 - 0010 0000 */ \
	((byte) & 0x10 ? '1' : '0'),/* TEST BIT 4 : 0x10 - 0001 0000 */ \
	((byte) & 0x08 ? '1' : '0'),/* TEST BIT 3 : 0x08 - 0000 1000 */ \
	((byte) & 0x04 ? '1' : '0'),/* TEST BIT 2 : 0x04 - 0000 0100 */ \
	((byte) & 0x02 ? '1' : '0'),/* TEST BIT 1 : 0x02 - 0000 0010 */ \
	((byte) & 0x01 ? '1' : '0') /* TEST BIT 0 : 0x01 - 0000 0001 */
	/* IF THERE IS A BIT AT A POSITION, SINCE WE BIT-WISE AND IT, THE
	 * RESULT WILL BE NON-ZERO -> WE OUTPUT 1, OTHERWISE WE OUTPUT 0 */

	/* THERE WAS A CORRECTION : I MOVED THE COMMENTS REGARDING TEST BIT 
	 * BEFORE THE CHARACTER '\'. THAT CHARACTER NEEDS TO BE THE LAST
	 * CHAR ON THE MACRO WHEN TERE ARE MULTIPLE LINES, OTHERWISE IT WILL
	 * BREAK. */

int main()
{
	int a=0; /* DECLARE AN INTEGER VARIABLE a,
		  * INITIALISE IT WITH 0 */

	scanf("%d",&a); /* READ THE INT AS A BASE-10 NUMBER */
	
	BYTE_DT *p = (BYTE_DT*)&a; /* unsigned char *p = (unsigned char*) &a; */
	/* WHAT THIS DOES: WE TAKE THE MEMORY ADDRESS OF a AND GIVE IT TO *p;
	 * SINCE THEY ARE OF DIFFERENT TYPES, WE PERFORM A POINTER CASTING SO
	 * AS TO BE ABLE TO KEEP IT AND TO ITERATE THROUGH MEMORY 1 BYTE AT
	 * A TIME. HAD WE USED int*, EVERY TIME WE DID A +1, WE WOULD GO
	 * 4 BYTES INSTEAD OF 1 */
	
	for(int i=sizeof(a)-1;i>=0;i--) /* SINCE a IS AN INT, IT WILL TAKE
					   4 BYTES OF MEMORY, AS SUCH,
					   sizeof(a) = 4 (SIZEOF TAKES THE
					   NUMBER OF BYTES A VARIABLE
					   OCCUPIES IN MEMORY */
	{
		printf(BYTE_TO_BINARY_PATTERN, BYTE_TO_BINARY(*(p+i)));
		/* PRINTS EACH BYTE. 
		 * BYTE_TO_BINARY_PATTERN - THE 8 %c I.E. PRINTS 8 CHARS
		 * BYTE_TO_BINARY - THE MACRO THAT CHECKS EACH BIT BY
		 * 			MEANS OF BITWISE AND.
		 * *(some pointer) - TAKES THE VALUE THAT EXISTS AT THE
		 * 			MEMORY ADDRESS WHICH IS BEING KEPT
		 * 			IN THE POINTER (SEE POINTERS).
		 * i WILL BE : 3, 2, 1, 0
		 * P + i MEANS : i BYTES * AFTER * THE ADDRESS THAT IS BEING
		 * 		KEPT AS THE POINTER.
		 * AS SUCH, p+i SHALL BE, p+3 (3 BYTES AFTER MEM ADDR OF A); 
		 * 			  p+2 (2 BYTES AFTER MEM ADDR OF A);
		 * 			  p+1 (1 BYTE AFTER MEM ADDR OF A);
		 * 			  p (MEM ADDR OF A);*/

		printf(" "); /* PRINT A SPACE S.T. EACH BYTE IS SEPARATED
				VISUALLY FROM THE NEXT ONE */
	}
	printf("\n"); /* SPECIFICALLY FOR LINUX, WE USE IT S.T. WHEN THE
			 PROGRAM ENDS, THE NEXT COMMAND WILL BE AFTER 
			 THE OUTPUT - NEXT LINE - THUS AVOIDING 
			 A CLUTTERED TTY */
	return 0;
}
